language: node_js
git:
  submodules: true
services:
  - docker
install:
  - npm install -g js-yaml
  - npm install jsonfile
before_script:
  - chmod +x ./integration/prepare.sh && ./integration/prepare.sh
script:
  - chmod +x build.sh && ./build.sh
after_success:
after_failure:
deploy: