language: node_js
node_js:
- '8'
git:
  submodules: false
  depth: false
if: tag IS blank
services:
- docker
before_install:
- sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends jq
- chmod +x ./integration/*.sh *.sh
install:
- npm install -g js-yaml
- npm install jsonfile
before_script:
- "./integration/prepare.sh"
script:
- "./build.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: "./integration/deploy.sh"
  on:
    branch: master
    condition: "$TRAVIS_EVENT_TYPE != cron"
deploy:
  provider: s3
  access_key_id: "$AWSAccessKeyId"
  secret_access_key: "$AWSSecretKey"
  bucket: "dexind"
  skip_cleanup: true
  region: us-east-1
  local_dir: "$TRAVIS_BUILD_DIR/build"
  upload-dir: "micropython-gigglebot/firmware/$(cat $TRAVIS_BUILD_DIR/integration/tag)"
  on:
    branch: master
    condition: "$TRAVIS_EVENT_TYPE != cron"
env:
  global:
  - secure: QVKYAQxrtZle9PYZol23KPQ1os6K0wZKVE5niP+6jf3lYYpURlbWAZ+VLY1AlpAynNaVgTqoZxf7GW1yfOkm1OrvfTPMAP7O6QW7lEg8f1+4QgGklfIW3Asb9LmBVQrTh7Zb5F8UErDMDoB3H2v/Z4bNs9SHp8OJHFtQJv67dlICdydvrxk2L3sQazUiOyR0VYZ6uvZG/Ci4xFTOyIlc00bO8yG9DNCwide7E6CzsL0xh2q9yhonr1aP0poxjOvcrTQV1EpNxZAk3DTflF9aHWJKdZjHZzLkSmiGGXGPK16jYPimCxPCxRqZqKaUeAjB0P0uQ0v1hIG+m5p+8k7rT90hsI+k/iVkizY7KBwI+DASdArospUAXWBgslfMMwCP+IZG5QANqIftYM0UYjsZmL+mXx6Vps0MDXScSrhQXY5VuX6742xjVKWnDtZvbvX7k7vn9ukhbWwGRq84MlPk00Gwk5LBSi51VWRN/ujsKO2va9qnX7VHqOvXwcXua4kIBQsfRkq5tzrkFwduynSMXzAzmTpon75bmrOdOj1fxAv27g+s1Ub32/qonrwGkzM1eFa3afQ5w/UaQdPiBddqxtIyYrse6xn0ciTQtGjbWXFH6/J2ggyZwTR4vBvZBTLU7EdIK1ngvXboi23waHHV1y8+VjUzlRBC78e3HiCqJq8=
  - secure: nzV73EQzfXBF5fJO/A9fiu7Y9H6zCZSEnztlsymplGT2gIEpf31ijisX10qZP/lByp//W21ijzu+PzLVNge2uEyZp0q+zRGymK67hUyRApF0sy37EPCJ9fXAZH9+5XswKUeV2T6UvFrvT0/rrjzmPuzSa+qitBenyKBJUbJDkhkRD1mh5F83F6T0D0JIULJBLMWpnxHIObDdxq83e++Db3Ql3tlzIfibF5QsqdR2F3B64hkSoq1K6R2ZifhjGN5eFVFHFI/58r2SqXswLElDfcpmKskbJGa2CzdlamK3kDXR596nAUnADUE7kcnecZUCyXfqmS46zBsH78ns0wocie/rilkpGWJKP8yAUWDkzk/0RaIz8i3zZB088p5fq/I+Ey+aFO8hPe/BRlsPpM8pmCnm4J3qNQ5JeoohhGCQN6R52Q0PB9+0qLQcK4n+KNdlIxz2ZrL4GaSuY1uxk222EGKOT4dR0Hy2WOjeVuOeUuEpqxBVucMzlEsYZ228vbVKg/Q/iIpar0zeZzwnGiMEgpBwFraaKqlL0/3u34jnM6tJBEhxu8UsqT14r8ZPdkJaNogDse4nGbJWMGBGoRKsVm6AnOmJFyftEvQj9EL3LrvCPvU7oi8bbgbVDAfIVLFgFYC19W+R3Mh8g1m5wfEwh1DajWI1Y1itNrwlt0e3Mxg=
  - secure: FyiGdU2HIWUzj3riSr8IOAROM52Phki6tCyBaiI3UpxwhpSNlR/bwBy0Z6uzY5yF7wj8iTrFW13fUgIawhMqUjN9urltCyX4RdOpefMchO2MZzBhRv3KR40hCpHltJl82XeoqUbO3rbKvye+rKWplqMIdycPkuSTgr7Q2qOFwTl6l6EseeccUZMMuQLXFxTZroGrud0D+RYkVgXd1iIjq7NfYlxGa3XK2ADkHlv0ai19U9WwN1leY7szm7CpxEBPS3TT3cTjdTOdLntTpSOFZq3rSFDTTZXN+AACn62gOVNJMYISGIBG/S4SWkOAuJCSxsjQiTtPIEPqYozsK2F6b0gjWFYSmVYEqe1KSWwDLmyn12QpGvEF/eMCftNKj0Q/3Nsd3epFS4nq/6CHIYTVxBweuxy/a2NFMs6Qe6R5hXuuyVJvNOVucQrsuDIwDa3WtJb3v2ax5ldLAyk8sAEqdehAWNH6KC1sAMJ3I7fUgUWtGa50EFfYOIB0ygoiCnDbn7aJBel0WlIA8PaXz6vZIW5CjMQlswh/YNt2emDC/iR0IdvMnYizADfHts2j9GCrRfPZpK3XEtp4U0wokbUllVhPOXloC+kxCJ2CaxE+1zrg/hj8JjGR0r2NLTi9iCstVP0SjPXc9eSplC/hfBPdb28gcM4PYb1Y8OBC8b2AgFs=
  - secure: otl0ePPJQpESUJ/9oKHITVg9TyJX86okysWhc2PYgvsNHMo35L9yE4SCjHZFjqAZOAzqnKVvis/QQTK10imn84lvEQ2dV7EUOGz37/iMqFb1XXac03S5yCeJxZhNR7Bu2PQh1UxKiHOHbzp3T++WSool2fh/sjTSPRutD2QEnp1OjnCgJf41EsdX2oGN0C9oQZRf51iGHzQBM8AEA5FW41qg5Qrkt0uLK6miyzcORfd5BnJ2zhBclMjbphNg1LpVMuSNxWQOV+sfK92WLoGzEdIk27OIYRR7oxmJ+7sLq/rUWfVHttAOCKC0K5WgJDRMuyLQb28nwOyx6pgKaC6X79/0JffdG995/tY/PRapLKI3Blfz1iHUisr3qlvuGUGdODlERHtvzDQL0m+n2locJeYTb0HZEjF8B7whTOhTjfHp1nJ+K7ioTjsQgrrAHuZvRQtUVZAaalnHAVCmbd3/ZfgT35x1lG0zZ4m81XpXuAZi1dSQk3q98DYxQEGjDZ5Qr8FLWpQyw5dD4yONlA5llCjinc0o33nV4Gq+91DIgTibNAzNzq17spMviD2SyVZjfUmffx2xgZAaHvKA3i9dtnTveAHEpKKXjWWovDSwEs0v9GLQRY0dm0NSAjAAEq5TFVBy2ltYxFZqE2AZvJfv1e+HRYbK/5Pic5sSkpfhnRo=
  - secure: iuOFKwYNzx2pJlCfFI0ZFIUvSwzmyoVeiKjyM+LNUe0v+WDZk4sN58xtjDZ74ih/qR85yNSGBxFX7HCj4YG13PhPbJzNBJRzVl4FF4fLi688oW83hMaHpu8xEqcGgGVJFz/wGZ+XnST/mPcIIzm85kuJ99XfbQWDUbQBqdAkOxlHJfZnScRW0kb3plLPcZck36x8f+BogSLrAdIc7IxWkR5U/E8igJ9nt9/vCzSl+LTrSzc6ApqVx5YyiwZefEGbdzGdGX+DH8K54laCTyXQ99Jrbf26+30yV89sz58Mz8sl1GGEOr9F8VfpGZNw4TskQJcIJEMYX3xMPzCMcuY/DOpa75mFCQxtYtqPBFA3p2xwrUbl0tM3a4mL2ZRYtQQ7aKVRwehL4ZMKrBbiNL7HRnQoSKze9MVmr2K6i9MFpUOrv/vtimMEGm2HXyVUuvvlD0Yb8KGSXeO7wAjDzhaNnppYFQukRgQchZGB7sp9X26bQotO8UF3bg18e99Ca3ZWNqgtYC2riRywV6LKgLTv52K0ghzpfEzXd9u70G8rUlI7m4ub+3qw+p2LbAiS/j94nvccsosuvaUkSkjtes9U0KHgpF5stoh4yIK0vQif1ZYEkK/Sb1AQPJ1J1uriYx9/5A1X5iU7vSLdxFk6y9iqmhFJBuWC7KV+GFac8zwaaYg=
